version: '3'

services:
    dummy:
        container_name: dummy
        build: .
        image: gcloud
        read_only: true

    c1:
        container_name: for-management
        image: gcloud
        tty: true
        volumes:
            - gcloud-config-administrator:/root/.config/gcloud

    c2:
        container_name: project-a
        image: gcloud
        tty: true
        volumes:
            - gcloud-config-developer:/root/.config/gcloud
        environment: 
            # - CLOUDSDK_ACTIVE_CONFIG_NAME=default
            - CLOUDSDK_CORE_PROJECT=project-a-451124
            - CLOUDSDK_COMPUTE_REGION=asia-northeast2
            - CLOUDSDK_COMPUTE_ZONE=asia-northeast2-b

    c3:
        container_name: project-b
        image: gcloud
        tty: true
        volumes:
            - gcloud-config-developer:/root/.config/gcloud
        environment: 
            # - CLOUDSDK_ACTIVE_CONFIG_NAME=www
            - CLOUDSDK_CORE_PROJECT=project-b-478522
            - CLOUDSDK_COMPUTE_REGION=asia-northeast1
            - CLOUDSDK_COMPUTE_ZONE=asia-northeast1-a
    
volumes:
    gcloud-config-administrator:
    gcloud-config-developer:

